### ISSUE TITLE
Debian 9 build

### ISSUE THREAD

**Issue by egberts** [DNSSEC-Tools/DNSSEC-Tools#1]
When attempting to build on Debian platform... 

    cd dnssec-tools/validator
    ./configure
    make

I get the following...

/bin/bash ../libtool --mode=compile gcc -g -O2 -Ulinux -Dlinux=linux -Ulinux -Dlinux=linux -DLIBVAL_CONFIGURED=1  -I../include   -c -o res_tsig.lo res_tsig.c
libtool: compile:  gcc -g -O2 -Ulinux -Dlinux=linux -Ulinux -Dlinux=linux -DLIBVAL_CONFIGURED=1 -I../include -c res_tsig.c  -fPIC -DPIC -o .libs/res_tsig.o
res_tsig.c: In function 'res_tsig_sign':
res_tsig.c:240:14: error: storage size of 'ctx' isn't known
     HMAC_CTX ctx;
              ^~~
res_tsig.c:277:9: warning: implicit declaration of function 'HMAC_CTX_init' [-Wimplicit-function-declaration]
         HMAC_CTX_init(&ctx);
         ^~~~~~~~~~~~~
res_tsig.c:351:9: warning: implicit declaration of function 'HMAC_CTX_cleanup' -Wimplicit-function-declaration]
         HMAC_CTX_cleanup(&ctx);
         ^~~~~~~~~~~~~~~~
Makefile:157: recipe for target 'res_tsig.lo' failed
make[1]: *** [res_tsig.lo] Error 1
make[1]: Leaving directory '/root/work/DNSSEC-Tools/dnssec-tools/validator/libsres'
<img width="1066" alt="screen shot 2018-08-08 at 4 36 50 pm" src="https://user-images.githubusercontent.com/10352354/43862999-5ecdc82a-9b29-11e8-8035-fc4f8043c95a.png">

**Comment by hardaker** [comment]
Thanks; Trying to merge two separate git repos and I think I missed a patch.  Will go find it.

**Comment by hardaker** [comment]
Fixed pushed in 86ee25091  ; I'll likely create a new release sometime this week too.
