### ISSUE TITLE
undefined reference to `HMAC_CTX_free'

### ISSUE THREAD

**Issue by egberts** [DNSSEC-Tools/DNSSEC-Tools#3]
git cloned this repo to a Debian 9, and:

    cd DNSSEC-tools
    ./configure
    ...
    dnssec-tools/validator/libsres/.libs/libsres.so: undefined reference to `HMAC_CTX_free'

I noticed that HMAC_CTX_free got introduced in openssl 1.1.0.

My openssl version is:

    OpenSSL> version
    OpenSSL 1.1.0f  25 May 2017

**Comment by egberts** [comment]
Fixed it by including the development package of OpenSSL 1.1.0f.

    sudo apt-get install libssl-dev
    make clean
    ./configure
    make -j4
    sudo make install

**Comment by hardaker** [comment]
Yeah, openssl keeps changing APIs about how to do things.  The latest version of dnssec-tools (2.2.3) works with the latest version of openssl but I'm not sure how far back in versions that it'll still work.  Unfortunately, they deprecated older ways of doing things and remove those memory management functions in place of new ones.  This was done in such a way that providing support for both APIs is near impossible, so the latest version of dnssec-tools tries to keep current with the later versions of openssl.
