### ISSUE TITLE
Site Down Request - DNSSEC Settings

### ISSUE THREAD

**Issue by KitchM** [DNSSEC-Tools/DNSSEC-Tools#4]
Since your site is in flux, I wondered if you could tell me where I can find the items needed by my registrar to complete the chain of trust.  They include, Digest, Key Tag, Digest Type and Algorithm Type.  I should point out that I have found my Algorithm Type to be RSASHA1.  But for the life of me I can't find the other settings.  Any help is greatly appreciated.  Thank you very much.

**Comment by hardaker** [comment]
If you have DNSSEC-Tools installed, then you can run the "getds" script and it will tell you the DS records that are needed by your registrar.

    # perl ./getds dnssec-tools.org
    --- DS records generated from queried keys of dnssec-tools.org:
      DNSSEC-TOOLS.ORG.	300	IN	DS	( 34816 5 2 
    	BF59736EAB4D7080065A8C96A714B86C23383478F69D9F7D887CBE9930B7A7A0 )
    	
      DNSSEC-TOOLS.ORG.	300	IN	DS	( 34816 5 1
    	45C062850924801C450E13EB7F2CD138BE5EE557 )
	
In this case, the digest is the long part (BF597...), the keytag is the first number (34816), the digest type is the third number (2 == SHA256) and the algorithm type is the second number (5).
