### ISSUE TITLE
Invalid define

### ISSUE THREAD

**Issue by arekm** [DNSSEC-Tools/DNSSEC-Tools#6]
https://github.com/DNSSEC-Tools/DNSSEC-Tools/blob/458198eb71b41da1bd521d55c243323f0a657a05/dnssec-tools/validator/apps/dnssec-check/DnssecCheckVersion.h

#define .2" 

is invalid here that got broken by 
https://github.com/DNSSEC-Tools/DNSSEC-Tools/commit/458198eb71b41da1bd521d55c243323f0a657a05#diff-794c228d8396d4beb1158838c5cb568a

**Comment by hardaker** [comment]
Ack, you're right.  Fixed in b67bd2e6d
